// Mocks generated by Mockito 5.4.4 from annotations
// in super_fitness_app/test/features/food/presentation/viewmodel/meals_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:super_fitness_app/features/food/data/models/meals_by_category_model.dart'
    as _i3;
import 'package:super_fitness_app/features/food/domain/usecases/get_food_by_category_usecase.dart'
    as _i6;
import 'package:super_fitness_app/features/home/data/models/meal_categories_response_model.dart'
    as _i2;
import 'package:super_fitness_app/features/home/domain/usecases/get_meal_categories_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMealCategoriesResponse_0 extends _i1.SmartFake
    implements _i2.MealCategoriesResponse {
  _FakeMealCategoriesResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMealsByCategoryModel_1 extends _i1.SmartFake
    implements _i3.MealsByCategoryModel {
  _FakeMealsByCategoryModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetMealCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMealCategoriesUseCase extends _i1.Mock
    implements _i4.GetMealCategoriesUseCase {
  MockGetMealCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.MealCategoriesResponse> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<_i2.MealCategoriesResponse>.value(
            _FakeMealCategoriesResponse_0(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i2.MealCategoriesResponse>);
}

/// A class which mocks [GetFoodByCategoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFoodByCategoryUseCase extends _i1.Mock
    implements _i6.GetFoodByCategoryUseCase {
  MockGetFoodByCategoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.MealsByCategoryModel> call(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [category],
        ),
        returnValue: _i5.Future<_i3.MealsByCategoryModel>.value(
            _FakeMealsByCategoryModel_1(
          this,
          Invocation.method(
            #call,
            [category],
          ),
        )),
      ) as _i5.Future<_i3.MealsByCategoryModel>);
}
