// Mocks generated by Mockito 5.4.4 from annotations
// in super_fitness_app/test/features/profile/presentation/viewmodel/profile_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/material.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:super_fitness_app/core/errors/api_result.dart' as _i5;
import 'package:super_fitness_app/features/auth/domain/responses/auth_response.dart'
    as _i2;
import 'package:super_fitness_app/features/auth/domain/usecase/sign_out_usecase.dart'
    as _i8;
import 'package:super_fitness_app/features/profile/domain/entity/user_entity.dart'
    as _i6;
import 'package:super_fitness_app/features/profile/domain/usecases/get_profile_data_usecase.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0<T> extends _i1.SmartFake
    implements _i2.AuthResponse<T> {
  _FakeAuthResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetProfileDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileDataUseCase extends _i1.Mock
    implements _i3.GetProfileDataUseCase {
  MockGetProfileDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.ApiResult<_i6.UserEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.ApiResult<_i6.UserEntity>>.value(
              _i7.dummyValue<_i5.ApiResult<_i6.UserEntity>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i6.UserEntity>>);
}

/// A class which mocks [SignOutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOutUseCase extends _i1.Mock implements _i8.SignOutUseCase {
  MockSignOutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AuthResponse<void>> call(_i9.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#call, [context]),
            returnValue: _i4.Future<_i2.AuthResponse<void>>.value(
              _FakeAuthResponse_0<void>(
                this,
                Invocation.method(#call, [context]),
              ),
            ),
          )
          as _i4.Future<_i2.AuthResponse<void>>);
}
