// Mocks generated by Mockito 5.4.4 from annotations
// in super_fitness_app/test/features/home/presentation/viewmodel/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:super_fitness_app/features/home/data/models/muscle_group_by_id_response_model.dart'
    as _i4;
import 'package:super_fitness_app/features/home/data/models/muscle_groups_response_model.dart'
    as _i3;
import 'package:super_fitness_app/features/home/data/models/muscles_response_model.dart'
    as _i2;
import 'package:super_fitness_app/features/home/domain/usecases/get_muscle_group_by_id_usecase.dart'
    as _i8;
import 'package:super_fitness_app/features/home/domain/usecases/get_muscle_groups_usecase.dart'
    as _i7;
import 'package:super_fitness_app/features/home/domain/usecases/get_random_muscles_usecase.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMusclesResponse_0 extends _i1.SmartFake
    implements _i2.MusclesResponse {
  _FakeMusclesResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMuscleGroupsResponse_1 extends _i1.SmartFake
    implements _i3.MuscleGroupsResponse {
  _FakeMuscleGroupsResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMuscleGroupByIdResponse_2 extends _i1.SmartFake
    implements _i4.MuscleGroupByIdResponse {
  _FakeMuscleGroupByIdResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetRandomMusclesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRandomMusclesUseCase extends _i1.Mock
    implements _i5.GetRandomMusclesUseCase {
  MockGetRandomMusclesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.MusclesResponse> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i6.Future<_i2.MusclesResponse>.value(_FakeMusclesResponse_0(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i6.Future<_i2.MusclesResponse>);
}

/// A class which mocks [GetMuscleGroupsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMuscleGroupsUseCase extends _i1.Mock
    implements _i7.GetMuscleGroupsUseCase {
  MockGetMuscleGroupsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.MuscleGroupsResponse> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<_i3.MuscleGroupsResponse>.value(
            _FakeMuscleGroupsResponse_1(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i6.Future<_i3.MuscleGroupsResponse>);
}

/// A class which mocks [GetMuscleGroupByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMuscleGroupByIdUseCase extends _i1.Mock
    implements _i8.GetMuscleGroupByIdUseCase {
  MockGetMuscleGroupByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.MuscleGroupByIdResponse> call(String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [groupId],
        ),
        returnValue: _i6.Future<_i4.MuscleGroupByIdResponse>.value(
            _FakeMuscleGroupByIdResponse_2(
          this,
          Invocation.method(
            #call,
            [groupId],
          ),
        )),
      ) as _i6.Future<_i4.MuscleGroupByIdResponse>);
}
