// Mocks generated by Mockito 5.4.4 from annotations
// in super_fitness_app/test/features/auth/api/datasource_implemenation/auth_remote_datasource_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:super_fitness_app/core/api/client/api_client.dart' as _i10;
import 'package:super_fitness_app/features/auth/data/models/forgetpasswordmodels/forget_password_request_model.dart'
    as _i13;
import 'package:super_fitness_app/features/auth/data/models/forgetpasswordmodels/reset_password_request_model.dart'
    as _i16;
import 'package:super_fitness_app/features/auth/data/models/forgetpasswordmodels/verify_code_request_model.dart'
    as _i15;
import 'package:super_fitness_app/features/auth/data/models/login_models/login_request_model.dart'
    as _i17;
import 'package:super_fitness_app/features/auth/data/models/login_models/login_response_model.dart'
    as _i3;
import 'package:super_fitness_app/features/auth/domain/responses/register_request_model.dart'
    as _i12;
import 'package:super_fitness_app/features/auth/domain/responses/register_response.dart'
    as _i2;
import 'package:super_fitness_app/features/home/data/models/meal_categories_response_model.dart'
    as _i9;
import 'package:super_fitness_app/features/home/data/models/muscle_group_by_id_response_model.dart'
    as _i8;
import 'package:super_fitness_app/features/home/data/models/muscle_groups_response_model.dart'
    as _i7;
import 'package:super_fitness_app/features/home/data/models/muscles_response_model.dart'
    as _i6;
import 'package:super_fitness_app/features/workouts/data/models/workouts/all_muscles_response.dart'
    as _i4;
import 'package:super_fitness_app/features/workouts/data/models/workouts/muscle_group_details_response.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRegisterResponse_0 extends _i1.SmartFake
    implements _i2.RegisterResponse {
  _FakeRegisterResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAllMusclesResponse_2 extends _i1.SmartFake
    implements _i4.AllMusclesResponse {
  _FakeAllMusclesResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMuscleGroupDetailsResponse_3 extends _i1.SmartFake
    implements _i5.MuscleGroupDetailsResponse {
  _FakeMuscleGroupDetailsResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMusclesResponse_4 extends _i1.SmartFake
    implements _i6.MusclesResponse {
  _FakeMusclesResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMuscleGroupsResponse_5 extends _i1.SmartFake
    implements _i7.MuscleGroupsResponse {
  _FakeMuscleGroupsResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMuscleGroupByIdResponse_6 extends _i1.SmartFake
    implements _i8.MuscleGroupByIdResponse {
  _FakeMuscleGroupByIdResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMealCategoriesResponse_7 extends _i1.SmartFake
    implements _i9.MealCategoriesResponse {
  _FakeMealCategoriesResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i10.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i2.RegisterResponse> register(
          _i12.RegisterRequestModel? registerRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [registerRequest],
        ),
        returnValue:
            _i11.Future<_i2.RegisterResponse>.value(_FakeRegisterResponse_0(
          this,
          Invocation.method(
            #register,
            [registerRequest],
          ),
        )),
      ) as _i11.Future<_i2.RegisterResponse>);

  @override
  _i11.Future<String> forgetPassword(
          _i13.ForgetPasswordRequestModel? forgetPasswordRequestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [forgetPasswordRequestModel],
        ),
        returnValue: _i11.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #forgetPassword,
            [forgetPasswordRequestModel],
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<String> verifyResetCode(
          _i15.VerifyCodeRequestModel? verifyResetCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [verifyResetCode],
        ),
        returnValue: _i11.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #verifyResetCode,
            [verifyResetCode],
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<String> resetPassword(
          _i16.ResetPasswordRequestModel? resetPasswordRequestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [resetPasswordRequestModel],
        ),
        returnValue: _i11.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #resetPassword,
            [resetPasswordRequestModel],
          ),
        )),
      ) as _i11.Future<String>);

  @override
  _i11.Future<_i3.LoginResponse> login(_i17.LoginRequest? loginRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [loginRequest],
        ),
        returnValue: _i11.Future<_i3.LoginResponse>.value(_FakeLoginResponse_1(
          this,
          Invocation.method(
            #login,
            [loginRequest],
          ),
        )),
      ) as _i11.Future<_i3.LoginResponse>);

  @override
  _i11.Future<_i4.AllMusclesResponse> getAllMuscles() => (super.noSuchMethod(
        Invocation.method(
          #getAllMuscles,
          [],
        ),
        returnValue:
            _i11.Future<_i4.AllMusclesResponse>.value(_FakeAllMusclesResponse_2(
          this,
          Invocation.method(
            #getAllMuscles,
            [],
          ),
        )),
      ) as _i11.Future<_i4.AllMusclesResponse>);

  @override
  _i11.Future<_i5.MuscleGroupDetailsResponse> getMusclesGroup(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMusclesGroup,
          [id],
        ),
        returnValue: _i11.Future<_i5.MuscleGroupDetailsResponse>.value(
            _FakeMuscleGroupDetailsResponse_3(
          this,
          Invocation.method(
            #getMusclesGroup,
            [id],
          ),
        )),
      ) as _i11.Future<_i5.MuscleGroupDetailsResponse>);

  @override
  _i11.Future<_i6.MusclesResponse> getRandomMuscles() => (super.noSuchMethod(
        Invocation.method(
          #getRandomMuscles,
          [],
        ),
        returnValue:
            _i11.Future<_i6.MusclesResponse>.value(_FakeMusclesResponse_4(
          this,
          Invocation.method(
            #getRandomMuscles,
            [],
          ),
        )),
      ) as _i11.Future<_i6.MusclesResponse>);

  @override
  _i11.Future<_i7.MuscleGroupsResponse> getMuscleGroups() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMuscleGroups,
          [],
        ),
        returnValue: _i11.Future<_i7.MuscleGroupsResponse>.value(
            _FakeMuscleGroupsResponse_5(
          this,
          Invocation.method(
            #getMuscleGroups,
            [],
          ),
        )),
      ) as _i11.Future<_i7.MuscleGroupsResponse>);

  @override
  _i11.Future<_i8.MuscleGroupByIdResponse> getMuscleGroupById(
          String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMuscleGroupById,
          [groupId],
        ),
        returnValue: _i11.Future<_i8.MuscleGroupByIdResponse>.value(
            _FakeMuscleGroupByIdResponse_6(
          this,
          Invocation.method(
            #getMuscleGroupById,
            [groupId],
          ),
        )),
      ) as _i11.Future<_i8.MuscleGroupByIdResponse>);

  @override
  _i11.Future<_i9.MealCategoriesResponse> getMealCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMealCategories,
          [],
        ),
        returnValue: _i11.Future<_i9.MealCategoriesResponse>.value(
            _FakeMealCategoriesResponse_7(
          this,
          Invocation.method(
            #getMealCategories,
            [],
          ),
        )),
      ) as _i11.Future<_i9.MealCategoriesResponse>);
}
