// Mocks generated by Mockito 5.4.4 from annotations
// in super_fitness_app/test/features/home/api/datasource_implemenation/muscles_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:super_fitness_app/core/api/client/api_client.dart' as _i7;
import 'package:super_fitness_app/features/auth/data/models/forgetpasswordmodels/forget_password_request_model.dart'
    as _i10;
import 'package:super_fitness_app/features/auth/data/models/forgetpasswordmodels/reset_password_request_model.dart'
    as _i13;
import 'package:super_fitness_app/features/auth/data/models/forgetpasswordmodels/verify_code_request_model.dart'
    as _i12;
import 'package:super_fitness_app/features/auth/data/models/login_models/login_request_model.dart'
    as _i14;
import 'package:super_fitness_app/features/auth/data/models/login_models/login_response_model.dart'
    as _i3;
import 'package:super_fitness_app/features/auth/domain/responses/register_request_model.dart'
    as _i9;
import 'package:super_fitness_app/features/auth/domain/responses/register_response.dart'
    as _i2;
import 'package:super_fitness_app/features/home/data/models/muscle_group_by_id_response_model.dart'
    as _i6;
import 'package:super_fitness_app/features/home/data/models/muscle_groups_response_model.dart'
    as _i5;
import 'package:super_fitness_app/features/home/data/models/muscles_response_model.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRegisterResponse_0 extends _i1.SmartFake
    implements _i2.RegisterResponse {
  _FakeRegisterResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMusclesResponse_2 extends _i1.SmartFake
    implements _i4.MusclesResponse {
  _FakeMusclesResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMuscleGroupsResponse_3 extends _i1.SmartFake
    implements _i5.MuscleGroupsResponse {
  _FakeMuscleGroupsResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMuscleGroupByIdResponse_4 extends _i1.SmartFake
    implements _i6.MuscleGroupByIdResponse {
  _FakeMuscleGroupByIdResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i7.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.RegisterResponse> register(
          _i9.RegisterRequestModel? registerRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [registerRequest],
        ),
        returnValue:
            _i8.Future<_i2.RegisterResponse>.value(_FakeRegisterResponse_0(
          this,
          Invocation.method(
            #register,
            [registerRequest],
          ),
        )),
      ) as _i8.Future<_i2.RegisterResponse>);

  @override
  _i8.Future<String> forgetPassword(
          _i10.ForgetPasswordRequestModel? forgetPasswordRequestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [forgetPasswordRequestModel],
        ),
        returnValue: _i8.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #forgetPassword,
            [forgetPasswordRequestModel],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<String> verifyResetCode(
          _i12.VerifyCodeRequestModel? verifyResetCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [verifyResetCode],
        ),
        returnValue: _i8.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #verifyResetCode,
            [verifyResetCode],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<String> resetPassword(
          _i13.ResetPasswordRequestModel? resetPasswordRequestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [resetPasswordRequestModel],
        ),
        returnValue: _i8.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #resetPassword,
            [resetPasswordRequestModel],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i3.LoginResponse> login(_i14.LoginRequest? loginRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [loginRequest],
        ),
        returnValue: _i8.Future<_i3.LoginResponse>.value(_FakeLoginResponse_1(
          this,
          Invocation.method(
            #login,
            [loginRequest],
          ),
        )),
      ) as _i8.Future<_i3.LoginResponse>);

  @override
  _i8.Future<_i4.MusclesResponse> getRandomMuscles() => (super.noSuchMethod(
        Invocation.method(
          #getRandomMuscles,
          [],
        ),
        returnValue:
            _i8.Future<_i4.MusclesResponse>.value(_FakeMusclesResponse_2(
          this,
          Invocation.method(
            #getRandomMuscles,
            [],
          ),
        )),
      ) as _i8.Future<_i4.MusclesResponse>);

  @override
  _i8.Future<_i5.MuscleGroupsResponse> getMuscleGroups() => (super.noSuchMethod(
        Invocation.method(
          #getMuscleGroups,
          [],
        ),
        returnValue: _i8.Future<_i5.MuscleGroupsResponse>.value(
            _FakeMuscleGroupsResponse_3(
          this,
          Invocation.method(
            #getMuscleGroups,
            [],
          ),
        )),
      ) as _i8.Future<_i5.MuscleGroupsResponse>);

  @override
  _i8.Future<_i6.MuscleGroupByIdResponse> getMuscleGroupById(String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMuscleGroupById,
          [groupId],
        ),
        returnValue: _i8.Future<_i6.MuscleGroupByIdResponse>.value(
            _FakeMuscleGroupByIdResponse_4(
          this,
          Invocation.method(
            #getMuscleGroupById,
            [groupId],
          ),
        )),
      ) as _i8.Future<_i6.MuscleGroupByIdResponse>);
}
