// Mocks generated by Mockito 5.4.4 from annotations
// in super_fitness_app/test/features/auth/presentation/views/register_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bloc/bloc.dart' as _i12;
import 'package:flutter/material.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:super_fitness_app/features/auth/data/models/login_models/login_request_model.dart'
    as _i8;
import 'package:super_fitness_app/features/auth/data/models/login_models/login_response_model.dart'
    as _i7;
import 'package:super_fitness_app/features/auth/domain/repo/auth_repo.dart'
    as _i3;
import 'package:super_fitness_app/features/auth/domain/responses/auth_response.dart'
    as _i2;
import 'package:super_fitness_app/features/auth/domain/responses/register_request_model.dart'
    as _i6;
import 'package:super_fitness_app/features/auth/domain/responses/register_response.dart'
    as _i5;
import 'package:super_fitness_app/features/auth/presentation/register/viewmodel/register_viewmodel/register_cubit.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0<T> extends _i1.SmartFake
    implements _i2.AuthResponse<T> {
  _FakeAuthResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i3.AuthRepo {
  MockAuthRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AuthResponse<_i5.RegisterResponse>> register(
          _i6.RegisterRequestModel? registerRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [registerRequest],
        ),
        returnValue: _i4.Future<_i2.AuthResponse<_i5.RegisterResponse>>.value(
            _FakeAuthResponse_0<_i5.RegisterResponse>(
          this,
          Invocation.method(
            #register,
            [registerRequest],
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<_i5.RegisterResponse>>);

  @override
  _i4.Future<_i2.AuthResponse<_i7.LoginResponse>> login(
          _i8.LoginRequest? loginRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [loginRequest],
        ),
        returnValue: _i4.Future<_i2.AuthResponse<_i7.LoginResponse>>.value(
            _FakeAuthResponse_0<_i7.LoginResponse>(
          this,
          Invocation.method(
            #login,
            [loginRequest],
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<_i7.LoginResponse>>);
}

/// A class which mocks [RegisterCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterCubit extends _i1.Mock implements _i9.RegisterCubit {
  MockRegisterCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isDataComplete => (super.noSuchMethod(
        Invocation.getter(#isDataComplete),
        returnValue: false,
      ) as bool);

  @override
  _i9.RegisterState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i10.dummyValue<_i9.RegisterState>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i9.RegisterState);

  @override
  _i4.Stream<_i9.RegisterState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i9.RegisterState>.empty(),
      ) as _i4.Stream<_i9.RegisterState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void setPersonalInfo({
    required String? firstName,
    required String? lastName,
    required String? email,
    required String? password,
    required String? rePassword,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setPersonalInfo,
          [],
          {
            #firstName: firstName,
            #lastName: lastName,
            #email: email,
            #password: password,
            #rePassword: rePassword,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setGender(String? gender) => super.noSuchMethod(
        Invocation.method(
          #setGender,
          [gender],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAge(int? age) => super.noSuchMethod(
        Invocation.method(
          #setAge,
          [age],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWeight(int? weight) => super.noSuchMethod(
        Invocation.method(
          #setWeight,
          [weight],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setHeight(int? height) => super.noSuchMethod(
        Invocation.method(
          #setHeight,
          [height],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setGoal({required String? goal}) => super.noSuchMethod(
        Invocation.method(
          #setGoal,
          [],
          {#goal: goal},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setActivityLevel({required String? activityLevel}) => super.noSuchMethod(
        Invocation.method(
          #setActivityLevel,
          [],
          {#activityLevel: activityLevel},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> submitRegistration() => (super.noSuchMethod(
        Invocation.method(
          #submitRegistration,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void logout(_i11.BuildContext? context) => super.noSuchMethod(
        Invocation.method(
          #logout,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i9.RegisterState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i12.Change<_i9.RegisterState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
