// Mocks generated by Mockito 5.4.4 from annotations
// in super_fitness_app/test/features/exercise/data/repositories_impl/exercise_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:super_fitness_app/features/exercise/data/datasource/exercise_remote_datasource.dart'
    as _i4;
import 'package:super_fitness_app/features/exercise/data/models/difficulty_levels_response.dart'
    as _i2;
import 'package:super_fitness_app/features/exercise/data/models/get_exercise_by_muscle_and_difficulty.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDifficultyLevelResponse_0 extends _i1.SmartFake
    implements _i2.DifficultyLevelResponse {
  _FakeDifficultyLevelResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetExerciseByMuscleAndDifficulty_1 extends _i1.SmartFake
    implements _i3.GetExerciseByMuscleAndDifficulty {
  _FakeGetExerciseByMuscleAndDifficulty_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExerciseRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRemoteDatasource extends _i1.Mock
    implements _i4.ExerciseRemoteDatasource {
  MockExerciseRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.DifficultyLevelResponse> getAllDifficultyLevels(
          String? primeMoverMuscleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDifficultyLevels,
          [primeMoverMuscleId],
        ),
        returnValue: _i5.Future<_i2.DifficultyLevelResponse>.value(
            _FakeDifficultyLevelResponse_0(
          this,
          Invocation.method(
            #getAllDifficultyLevels,
            [primeMoverMuscleId],
          ),
        )),
      ) as _i5.Future<_i2.DifficultyLevelResponse>);

  @override
  _i5.Future<_i3.GetExerciseByMuscleAndDifficulty>
      getExerciseByMuscleAndDifficulty(
    String? primeMoverMuscleId,
    String? difficultyLevelId,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getExerciseByMuscleAndDifficulty,
              [
                primeMoverMuscleId,
                difficultyLevelId,
              ],
            ),
            returnValue: _i5.Future<_i3.GetExerciseByMuscleAndDifficulty>.value(
                _FakeGetExerciseByMuscleAndDifficulty_1(
              this,
              Invocation.method(
                #getExerciseByMuscleAndDifficulty,
                [
                  primeMoverMuscleId,
                  difficultyLevelId,
                ],
              ),
            )),
          ) as _i5.Future<_i3.GetExerciseByMuscleAndDifficulty>);
}
