// Mocks generated by Mockito 5.4.4 from annotations
// in super_fitness_app/test/features/workouts/presentation/viewmodel/workouts_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:super_fitness_app/features/auth/domain/responses/auth_response.dart'
    as _i2;
import 'package:super_fitness_app/features/workouts/data/models/workouts/all_muscles_response.dart'
    as _i5;
import 'package:super_fitness_app/features/workouts/data/models/workouts/muscle_group_details_response.dart'
    as _i6;
import 'package:super_fitness_app/features/workouts/domain/usecase/workouts_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0<T> extends _i1.SmartFake
    implements _i2.AuthResponse<T> {
  _FakeAuthResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WorkoutsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutsUseCase extends _i1.Mock implements _i3.WorkoutsUseCase {
  MockWorkoutsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AuthResponse<_i5.AllMusclesResponse>> invoke() =>
      (super.noSuchMethod(
            Invocation.method(#invoke, []),
            returnValue:
                _i4.Future<_i2.AuthResponse<_i5.AllMusclesResponse>>.value(
                  _FakeAuthResponse_0<_i5.AllMusclesResponse>(
                    this,
                    Invocation.method(#invoke, []),
                  ),
                ),
          )
          as _i4.Future<_i2.AuthResponse<_i5.AllMusclesResponse>>);

  @override
  _i4.Future<_i2.AuthResponse<_i6.MuscleGroupDetailsResponse>> getMusclesGroup(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMusclesGroup, [id]),
            returnValue: _i4.Future<
              _i2.AuthResponse<_i6.MuscleGroupDetailsResponse>
            >.value(
              _FakeAuthResponse_0<_i6.MuscleGroupDetailsResponse>(
                this,
                Invocation.method(#getMusclesGroup, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.AuthResponse<_i6.MuscleGroupDetailsResponse>>);
}
