// Mocks generated by Mockito 5.4.4 from annotations
// in super_fitness_app/test/features/auth/domain/usecases/login_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:super_fitness_app/features/auth/data/models/login_models/login_request_model.dart'
    as _i8;
import 'package:super_fitness_app/features/auth/data/models/login_models/login_response_model.dart'
    as _i7;
import 'package:super_fitness_app/features/auth/domain/repo/auth_repo.dart'
    as _i3;
import 'package:super_fitness_app/features/auth/domain/responses/auth_response.dart'
    as _i2;
import 'package:super_fitness_app/features/auth/domain/responses/register_request_model.dart'
    as _i6;
import 'package:super_fitness_app/features/auth/domain/responses/register_response.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0<T> extends _i1.SmartFake
    implements _i2.AuthResponse<T> {
  _FakeAuthResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i3.AuthRepo {
  MockAuthRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AuthResponse<String>> forgetPassword(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [email],
        ),
        returnValue: _i4.Future<_i2.AuthResponse<String>>.value(
            _FakeAuthResponse_0<String>(
          this,
          Invocation.method(
            #forgetPassword,
            [email],
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<String>>);

  @override
  _i4.Future<_i2.AuthResponse<String>> verifyCode(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyCode,
          [code],
        ),
        returnValue: _i4.Future<_i2.AuthResponse<String>>.value(
            _FakeAuthResponse_0<String>(
          this,
          Invocation.method(
            #verifyCode,
            [code],
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<String>>);

  @override
  _i4.Future<_i2.AuthResponse<String>> resetPassword(
    String? email,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [
            email,
            newPassword,
          ],
        ),
        returnValue: _i4.Future<_i2.AuthResponse<String>>.value(
            _FakeAuthResponse_0<String>(
          this,
          Invocation.method(
            #resetPassword,
            [
              email,
              newPassword,
            ],
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<String>>);

  @override
  _i4.Future<_i2.AuthResponse<_i5.RegisterResponse>> register(
          _i6.RegisterRequestModel? registerRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [registerRequest],
        ),
        returnValue: _i4.Future<_i2.AuthResponse<_i5.RegisterResponse>>.value(
            _FakeAuthResponse_0<_i5.RegisterResponse>(
          this,
          Invocation.method(
            #register,
            [registerRequest],
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<_i5.RegisterResponse>>);

  @override
  _i4.Future<_i2.AuthResponse<_i7.LoginResponse>> login(
          _i8.LoginRequest? loginRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [loginRequest],
        ),
        returnValue: _i4.Future<_i2.AuthResponse<_i7.LoginResponse>>.value(
            _FakeAuthResponse_0<_i7.LoginResponse>(
          this,
          Invocation.method(
            #login,
            [loginRequest],
          ),
        )),
      ) as _i4.Future<_i2.AuthResponse<_i7.LoginResponse>>);
}
