// Mocks generated by Mockito 5.4.4 from annotations
// in super_fitness_app/test/features/profile/data/repositories_impl/profile_repositories_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:super_fitness_app/core/errors/api_result.dart' as _i4;
import 'package:super_fitness_app/features/profile/data/datasource/profile_remote_datasource.dart'
    as _i2;
import 'package:super_fitness_app/features/profile/data/models/profile_response.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProfileRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDatasource extends _i1.Mock
    implements _i2.ProfileRemoteDatasource {
  MockProfileRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.ProfileResponse>> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i3.Future<_i4.ApiResult<_i5.ProfileResponse>>.value(
              _i6.dummyValue<_i4.ApiResult<_i5.ProfileResponse>>(
                this,
                Invocation.method(#getProfile, []),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.ProfileResponse>>);
}
